window.FONT_DATA = [
    { value: "Inter, sans-serif", name: "Inter" },
    { value: "Source Sans Pro, sans-serif", name: "Source Sans Pro" },
    { value: "Ubuntu, sans-serif", name: "Ubuntu" },
    { value: "Noto Sans, sans-serif", name: "Noto Sans" },
    { value: "PT Sans, sans-serif", name: "PT Sans" },
    { value: "Work Sans, sans-serif", name: "Work Sans" },
    { value: "Quicksand, sans-serif", name: "Quicksand" },
    { value: "Comfortaa, cursive", name: "Comfortaa" },
    { value: "Fredoka One, cursive", name: "Fredoka One" },
    { value: "Righteous, cursive", name: "Righteous" },
    { value: "Bangers, cursive", name: "Bangers" },
    { value: "Permanent Marker, cursive", name: "Permanent Marker" },
    { value: "Caveat, cursive", name: "Caveat" },
    { value: "Indie Flower, cursive", name: "Indie Flower" },
    { value: "Shadows Into Light, cursive", name: "Shadows Into Light" },
    { value: "Kalam, cursive", name: "Kalam" },
    { value: "Patrick Hand, cursive", name: "Patrick Hand" },
    { value: "Architects Daughter, cursive", name: "Architects Daughter" },
    { value: "Gloria Hallelujah, cursive", name: "Gloria Hallelujah" },
    { value: "Rock Salt, cursive", name: "Rock Salt" },
    { value: "Satisfy, cursive", name: "Satisfy" },
    { value: "Great Vibes, cursive", name: "Great Vibes" },
    { value: "Alex Brush, cursive", name: "Alex Brush" },
    { value: "Allura, cursive", name: "Allura" },
    { value: "Tangerine, cursive", name: "Tangerine" },
    { value: "Sacramento, cursive", name: "Sacramento" },
    { value: "Dawning of a New Day, cursive", name: "Dawning of a New Day" },
    { value: "Petit Formal Script, cursive", name: "Petit Formal Script" },
    { value: "Rouge Script, cursive", name: "Rouge Script" },
    { value: "Italianno, cursive", name: "Italianno" },
    { value: "Mr De Haviland, cursive", name: "Mr De Haviland" },
    { value: "Mrs Saint Delafield, cursive", name: "Mrs Saint Delafield" },
    { value: "Crimson Text, serif", name: "Crimson Text" },
    { value: "Libre Baskerville, serif", name: "Libre Baskerville" },
    { value: "Source Serif Pro, serif", name: "Source Serif Pro" },
    { value: "Noto Serif, serif", name: "Noto Serif" },
    { value: "PT Serif, serif", name: "PT Serif" },
    { value: "EB Garamond, serif", name: "EB Garamond" },
    { value: "Cormorant Garamond, serif", name: "Cormorant Garamond" },
    { value: "Bitter, serif", name: "Bitter" },
    { value: "Domine, serif", name: "Domine" },
    { value: "Spectral, serif", name: "Spectral" },
    { value: "Fraunces, serif", name: "Fraunces" },
    { value: "Recursive, sans-serif", name: "Recursive" },
    { value: "JetBrains Mono, monospace", name: "JetBrains Mono" },
    { value: "Source Code Pro, monospace", name: "Source Code Pro" },
    { value: "IBM Plex Mono, monospace", name: "IBM Plex Mono" },
    { value: "Space Mono, monospace", name: "Space Mono" },
    { value: "Roboto Mono, monospace", name: "Roboto Mono" },
    { value: "Inconsolata, monospace", name: "Inconsolata" },
    { value: "Cousine, monospace", name: "Cousine" },
    { value: "Anonymous Pro, monospace", name: "Anonymous Pro" },
    { value: "VT323, monospace", name: "VT323" },
    { value: "Press Start 2P, cursive", name: "Press Start 2P" },
    { value: "Orbitron, sans-serif", name: "Orbitron" },
    { value: "Audiowide, cursive", name: "Audiowide" },
    { value: "Russo One, sans-serif", name: "Russo One" },
    { value: "Black Ops One, cursive", name: "Black Ops One" },
    { value: "Chakra Petch, sans-serif", name: "Chakra Petch" },
    { value: "Rajdhani, sans-serif", name: "Rajdhani" },
    { value: "Exo 2, sans-serif", name: "Exo 2" },
    { value: "Titillium Web, sans-serif", name: "Titillium Web" },
    { value: "Josefin Sans, sans-serif", name: "Josefin Sans" },
    { value: "Abel, sans-serif", name: "Abel" },
    { value: "Anton, sans-serif", name: "Anton" },
    { value: "Barlow, sans-serif", name: "Barlow" },
    { value: "Barlow Condensed, sans-serif", name: "Barlow Condensed" },
    { value: "Barlow Semi Condensed, sans-serif", name: "Barlow Semi Condensed" },
    { value: "Bungee, cursive", name: "Bungee" },
    { value: "Bungee Hairline, cursive", name: "Bungee Hairline" },
    { value: "Bungee Inline, cursive", name: "Bungee Inline" },
    { value: "Bungee Outline, cursive", name: "Bungee Outline" },
    { value: "Bungee Shade, cursive", name: "Bungee Shade" },
    { value: "Cabin, sans-serif", name: "Cabin" },
    { value: "Cabin Condensed, sans-serif", name: "Cabin Condensed" },
    { value: "Cabin Sketch, cursive", name: "Cabin Sketch" },
    { value: "Caveat Brush, cursive", name: "Caveat Brush" },
    { value: "Chewy, cursive", name: "Chewy" },
    { value: "Comic Neue, cursive", name: "Comic Neue" },
    { value: "Creepster, cursive", name: "Creepster" },
    { value: "Eater, cursive", name: "Eater" },
    { value: "Emblema One, cursive", name: "Emblema One" },
    { value: "Fascinate, cursive", name: "Fascinate" },
    { value: "Fascinate Inline, cursive", name: "Fascinate Inline" },
    { value: "Faster One, cursive", name: "Faster One" },
    { value: "Finger Paint, cursive", name: "Finger Paint" },
    { value: "Freckle Face, cursive", name: "Freckle Face" },
    { value: "Frijole, cursive", name: "Frijole" },
    { value: "Fruktur, cursive", name: "Fruktur" },
    { value: "Griffy, cursive", name: "Griffy" },
    { value: "Henny Penny, cursive", name: "Henny Penny" },
    { value: "Irish Grover, cursive", name: "Irish Grover" },
    { value: "Kavoon, cursive", name: "Kavoon" },
    { value: "Londrina Outline, cursive", name: "Londrina Outline" },
    { value: "Londrina Shadow, cursive", name: "Londrina Shadow" },
    { value: "Londrina Sketch, cursive", name: "Londrina Sketch" },
    { value: "Londrina Solid, cursive", name: "Londrina Solid" },
    { value: "Macondo, cursive", name: "Macondo" },
    { value: "Macondo Swash Caps, cursive", name: "Macondo Swash Caps" },
    { value: "MedievalSharp, cursive", name: "MedievalSharp" },
    { value: "Megrim, cursive", name: "Megrim" },
    { value: "Miltonian, cursive", name: "Miltonian" },
    { value: "Miltonian Tattoo, cursive", name: "Miltonian Tattoo" },
    { value: "Monofett, cursive", name: "Monofett" },
    { value: "Monoton, cursive", name: "Monoton" },
    { value: "Mountains of Christmas, cursive", name: "Mountains of Christmas" },
    { value: "Nabla, cursive", name: "Nabla" },
    { value: "Nerko One, cursive", name: "Nerko One" },
    { value: "Niconne, cursive", name: "Niconne" },
    { value: "Nosifer, cursive", name: "Nosifer" },
    { value: "Nova Cut, cursive", name: "Nova Cut" },
    { value: "Nova Flat, cursive", name: "Nova Flat" },
    { value: "Nova Mono, monospace", name: "Nova Mono" },
    { value: "Nova Oval, cursive", name: "Nova Oval" },
    { value: "Nova Round, cursive", name: "Nova Round" },
    { value: "Nova Script, cursive", name: "Nova Script" },
    { value: "Nova Slim, cursive", name: "Nova Slim" },
    { value: "Nova Square, cursive", name: "Nova Square" },
    { value: "Odibee Sans, cursive", name: "Odibee Sans" },
    { value: "Oregano, cursive", name: "Oregano" },
    { value: "Original Surfer, cursive", name: "Original Surfer" },
    { value: "Over the Rainbow, cursive", name: "Over the Rainbow" },
    { value: "Overlock, cursive", name: "Overlock" },
    { value: "Overlock SC, cursive", name: "Overlock SC" },
    { value: "Ovo, serif", name: "Ovo" },
    { value: "Oxygen, sans-serif", name: "Oxygen" },
    { value: "Oxygen Mono, monospace", name: "Oxygen Mono" },
    { value: "PT Sans Caption, sans-serif", name: "PT Sans Caption" },
    { value: "PT Sans Narrow, sans-serif", name: "PT Sans Narrow" },
    { value: "PT Serif Caption, serif", name: "PT Serif Caption" },
    { value: "Piedra, cursive", name: "Piedra" },
    { value: "Pirata One, cursive", name: "Pirata One" },
    { value: "Plaster, cursive", name: "Plaster" },
    { value: "Play, sans-serif", name: "Play" },
    { value: "Podkova, serif", name: "Podkova" },
    { value: "Poller One, cursive", name: "Poller One" },
    { value: "Poly, serif", name: "Poly" },
    { value: "Pompiere, cursive", name: "Pompiere" },
    { value: "Pontano Sans, sans-serif", name: "Pontano Sans" },
    { value: "Port Lligat Sans, sans-serif", name: "Port Lligat Sans" },
    { value: "Port Lligat Slab, serif", name: "Port Lligat Slab" },
    { value: "Prata, serif", name: "Prata" },
    { value: "Preahvihear, sans-serif", name: "Preahvihear" },
    { value: "Princess Sofia, cursive", name: "Princess Sofia" },
    { value: "Prociono, serif", name: "Prociono" },
    { value: "Prosto One, cursive", name: "Prosto One" },
    { value: "Puritan, sans-serif", name: "Puritan" },
    { value: "Purple Purse, cursive", name: "Purple Purse" },
    { value: "Quando, serif", name: "Quando" },
    { value: "Quantico, sans-serif", name: "Quantico" },
    { value: "Quattrocento, serif", name: "Quattrocento" },
    { value: "Quattrocento Sans, sans-serif", name: "Quattrocento Sans" },
    { value: "Questrial, sans-serif", name: "Questrial" },
    { value: "Quintessential, cursive", name: "Quintessential" },
    { value: "Qwigley, cursive", name: "Qwigley" },
    { value: "Racing Sans One, cursive", name: "Racing Sans One" },
    { value: "Radley, serif", name: "Radley" },
    { value: "Raleway, sans-serif", name: "Raleway" },
    { value: "Raleway Dots, cursive", name: "Raleway Dots" },
    { value: "Rammetto One, cursive", name: "Rammetto One" },
    { value: "Ranchers, cursive", name: "Ranchers" },
    { value: "Rancho, cursive", name: "Rancho" },
    { value: "Rationale, sans-serif", name: "Rationale" },
    { value: "Redressed, cursive", name: "Redressed" },
    { value: "Reenie Beanie, cursive", name: "Reenie Beanie" },
    { value: "Revalia, cursive", name: "Revalia" },
    { value: "Ribeye, cursive", name: "Ribeye" },
    { value: "Ribeye Marrow, cursive", name: "Ribeye Marrow" },
    { value: "Risque, cursive", name: "Risque" },
    { value: "Roboto Condensed, sans-serif", name: "Roboto Condensed" },
    { value: "Roboto Slab, serif", name: "Roboto Slab" },
    { value: "Rochester, cursive", name: "Rochester" },
    { value: "Rokkitt, serif", name: "Rokkitt" },
    { value: "Romanesco, cursive", name: "Romanesco" },
    { value: "Ropa Sans, sans-serif", name: "Ropa Sans" },
    { value: "Rosario, sans-serif", name: "Rosario" },
    { value: "Rosarivo, serif", name: "Rosarivo" },
    { value: "Rozha One, serif", name: "Rozha One" },
    { value: "Rubik, sans-serif", name: "Rubik" },
    { value: "Rubik Beastly, cursive", name: "Rubik Beastly" },
    { value: "Rubik Bubbles, cursive", name: "Rubik Bubbles" },
    { value: "Rubik Burned, cursive", name: "Rubik Burned" },
    { value: "Rubik Dirt, cursive", name: "Rubik Dirt" },
    { value: "Rubik Distressed, cursive", name: "Rubik Distressed" },
    { value: "Rubik Gemstones, cursive", name: "Rubik Gemstones" },
    { value: "Rubik Glitch, cursive", name: "Rubik Glitch" },
    { value: "Rubik Iso, cursive", name: "Rubik Iso" },
    { value: "Rubik Marker Hatch, cursive", name: "Rubik Marker Hatch" },
    { value: "Rubik Maze, cursive", name: "Rubik Maze" },
    { value: "Rubik Microbe, cursive", name: "Rubik Microbe" },
    { value: "Rubik Mono One, sans-serif", name: "Rubik Mono One" },
    { value: "Rubik Moonrocks, cursive", name: "Rubik Moonrocks" },
    { value: "Rubik Puddles, cursive", name: "Rubik Puddles" },
    { value: "Rubik Spray Paint, cursive", name: "Rubik Spray Paint" },
    { value: "Rubik Storm, cursive", name: "Rubik Storm" },
    { value: "Rubik Vinyl, cursive", name: "Rubik Vinyl" },
    { value: "Rubik Wet Paint, cursive", name: "Rubik Wet Paint" },
    { value: "Ruda, sans-serif", name: "Ruda" },
    { value: "Rufina, serif", name: "Rufina" },
    { value: "Ruge Boogie, cursive", name: "Ruge Boogie" },
    { value: "Ruluko, sans-serif", name: "Ruluko" },
    { value: "Rum Raisin, sans-serif", name: "Rum Raisin" },
    { value: "Ruslan Display, cursive", name: "Ruslan Display" },
    { value: "Ruthie, cursive", name: "Ruthie" },
    { value: "Rye, cursive", name: "Rye" },
    { value: "Sahitya, serif", name: "Sahitya" },
    { value: "Sail, cursive", name: "Sail" },
    { value: "Salsa, cursive", name: "Salsa" },
    { value: "Sanchez, serif", name: "Sanchez" },
    { value: "Sancreek, cursive", name: "Sancreek" },
    { value: "Sansita, sans-serif", name: "Sansita" },
    { value: "Sansita Swashed, cursive", name: "Sansita Swashed" },
    { value: "Sarabun, sans-serif", name: "Sarabun" },
    { value: "Sarala, sans-serif", name: "Sarala" },
    { value: "Sarina, cursive", name: "Sarina" },
    { value: "Sarpanch, sans-serif", name: "Sarpanch" },
    { value: "Sawarabi Gothic, sans-serif", name: "Sawarabi Gothic" },
    { value: "Sawarabi Mincho, serif", name: "Sawarabi Mincho" },
    { value: "Scada, sans-serif", name: "Scada" },
    { value: "Scheherazade New, serif", name: "Scheherazade New" },
    { value: "Schoolbell, cursive", name: "Schoolbell" },
    { value: "Scope One, serif", name: "Scope One" },
    { value: "Seaweed Script, cursive", name: "Seaweed Script" },
    { value: "Secular One, sans-serif", name: "Secular One" },
    { value: "Sedgwick Ave, cursive", name: "Sedgwick Ave" },
    { value: "Sedgwick Ave Display, cursive", name: "Sedgwick Ave Display" },
    { value: "Sen, sans-serif", name: "Sen" },
    { value: "Sevillana, cursive", name: "Sevillana" },
    { value: "Seymour One, sans-serif", name: "Seymour One" },
    { value: "Shadows Into Light Two, cursive", name: "Shadows Into Light Two" },
    { value: "Shanti, sans-serif", name: "Shanti" },
    { value: "Share, cursive", name: "Share" },
    { value: "Share Tech, sans-serif", name: "Share Tech" },
    { value: "Share Tech Mono, monospace", name: "Share Tech Mono" },
    { value: "Shippori Antique, serif", name: "Shippori Antique" },
    { value: "Shippori Antique B1, serif", name: "Shippori Antique B1" },
    { value: "Shippori Mincho, serif", name: "Shippori Mincho" },
    { value: "Shippori Mincho B1, serif", name: "Shippori Mincho B1" },
    { value: "Shojumaru, cursive", name: "Shojumaru" },
    { value: "Short Stack, cursive", name: "Short Stack" },
    { value: "Shrikhand, cursive", name: "Shrikhand" },
    { value: "Siemreap, cursive", name: "Siemreap" },
    { value: "Sigmar One, cursive", name: "Sigmar One" },
    { value: "Signika, sans-serif", name: "Signika" },
    { value: "Signika Negative, sans-serif", name: "Signika Negative" },
    { value: "Simonetta, serif", name: "Simonetta" },
    { value: "Single Day, cursive", name: "Single Day" },
    { value: "Sintony, sans-serif", name: "Sintony" },
    { value: "Sirin Stencil, cursive", name: "Sirin Stencil" },
    { value: "Six Caps, sans-serif", name: "Six Caps" },
    { value: "Skranji, cursive", name: "Skranji" },
    { value: "Slabo 13px, serif", name: "Slabo 13px" },
    { value: "Slabo 27px, serif", name: "Slabo 27px" },
    { value: "Slackey, cursive", name: "Slackey" },
    { value: "Smokum, cursive", name: "Smokum" },
    { value: "Smythe, cursive", name: "Smythe" },
    { value: "Sniglet, cursive", name: "Sniglet" },
    { value: "Snippet, sans-serif", name: "Snippet" },
    { value: "Snowburst One, cursive", name: "Snowburst One" },
    { value: "Sofadi One, cursive", name: "Sofadi One" },
    { value: "Sofia, cursive", name: "Sofia" },
    { value: "Solway, serif", name: "Solway" },
    { value: "Song Myung, serif", name: "Song Myung" },
    { value: "Sonsie One, cursive", name: "Sonsie One" },
    { value: "Sora, sans-serif", name: "Sora" },
    { value: "Sorts Mill Goudy, serif", name: "Sorts Mill Goudy" },
    { value: "Space Grotesk, sans-serif", name: "Space Grotesk" },
    { value: "Special Elite, cursive", name: "Special Elite" },
    { value: "Spicy Rice, cursive", name: "Spicy Rice" },
    { value: "Spinnaker, sans-serif", name: "Spinnaker" },
    { value: "Spirax, cursive", name: "Spirax" },
    { value: "Squada One, cursive", name: "Squada One" },
    { value: "Sree Krushnadevaraya, serif", name: "Sree Krushnadevaraya" },
    { value: "Sriracha, cursive", name: "Sriracha" },
    { value: "Srisakdi, cursive", name: "Srisakdi" },
    { value: "Staatliches, cursive", name: "Staatliches" },
    { value: "Stalemate, cursive", name: "Stalemate" },
    { value: "Stalinist One, cursive", name: "Stalinist One" },
    { value: "Stardos Stencil, cursive", name: "Stardos Stencil" },
    { value: "Stint Ultra Condensed, serif", name: "Stint Ultra Condensed" },
    { value: "Stint Ultra Expanded, serif", name: "Stint Ultra Expanded" },
    { value: "Stoke, serif", name: "Stoke" },
    { value: "Strait, sans-serif", name: "Strait" },
    { value: "Stylish, sans-serif", name: "Stylish" },
    { value: "Sue Ellen Francisco, cursive", name: "Sue Ellen Francisco" },
    { value: "Suez One, sans-serif", name: "Suez One" },
    { value: "Sulphur Point, sans-serif", name: "Sulphur Point" },
    { value: "Sumana, serif", name: "Sumana" },
    { value: "Sunflower, sans-serif", name: "Sunflower" },
    { value: "Sunshiney, cursive", name: "Sunshiney" },
    { value: "Supermercado One, cursive", name: "Supermercado One" },
    { value: "Sura, serif", name: "Sura" },
    { value: "Suranna, serif", name: "Suranna" },
    { value: "Suravaram, serif", name: "Suravaram" },
    { value: "Suwannaphum, serif", name: "Suwannaphum" },
    { value: "Swanky and Moo Moo, cursive", name: "Swanky and Moo Moo" },
    { value: "Syncopate, sans-serif", name: "Syncopate" },
    { value: "Syne, sans-serif", name: "Syne" },
    { value: "Syne Mono, monospace", name: "Syne Mono" },
    { value: "Syne Tactile, cursive", name: "Syne Tactile" },
    { value: "Tajawal, sans-serif", name: "Tajawal" },
    { value: "Taprom, cursive", name: "Taprom" },
    { value: "Tauri, sans-serif", name: "Tauri" },
    { value: "Taviraj, serif", name: "Taviraj" },
    { value: "Teko, sans-serif", name: "Teko" },
    { value: "Telex, sans-serif", name: "Telex" },
    { value: "Tenali Ramakrishna, sans-serif", name: "Tenali Ramakrishna" },
    { value: "Tenor Sans, sans-serif", name: "Tenor Sans" },
    { value: "Text Me One, sans-serif", name: "Text Me One" },
    { value: "Thasadith, sans-serif", name: "Thasadith" },
    { value: "The Girl Next Door, cursive", name: "The Girl Next Door" },
    { value: "Tienne, serif", name: "Tienne" },
    { value: "Tillana, cursive", name: "Tillana" },
    { value: "Timmana, sans-serif", name: "Timmana" },
    { value: "Tinos, serif", name: "Tinos" },
    { value: "Titan One, cursive", name: "Titan One" },
    { value: "Tomorrow, sans-serif", name: "Tomorrow" },
    { value: "Trade Winds, cursive", name: "Trade Winds" },
    { value: "Trirong, serif", name: "Trirong" },
    { value: "Trispace, sans-serif", name: "Trispace" },
    { value: "Trocchi, serif", name: "Trocchi" },
    { value: "Trochut, cursive", name: "Trochut" },
    { value: "Truculenta, sans-serif", name: "Truculenta" },
    { value: "Trykker, serif", name: "Trykker" },
    { value: "Tulpen One, cursive", name: "Tulpen One" },
    { value: "Turret Road, sans-serif", name: "Turret Road" },
    { value: "Twinkle Star, cursive", name: "Twinkle Star" },
    { value: "Ubuntu Condensed, sans-serif", name: "Ubuntu Condensed" },
    { value: "Ubuntu Mono, monospace", name: "Ubuntu Mono" },
    { value: "Ultra, serif", name: "Ultra" },
    { value: "Uncial Antiqua, cursive", name: "Uncial Antiqua" },
    { value: "Underdog, cursive", name: "Underdog" },
    { value: "Unica One, cursive", name: "Unica One" },
    { value: "UnifrakturCook, cursive", name: "UnifrakturCook" },
    { value: "UnifrakturMaguntia, cursive", name: "UnifrakturMaguntia" },
    { value: "Unkempt, cursive", name: "Unkempt" },
    { value: "Unlock, cursive", name: "Unlock" },
    { value: "Unna, serif", name: "Unna" },
    { value: "Vampiro One, cursive", name: "Vampiro One" },
    { value: "Varela, sans-serif", name: "Varela" },
    { value: "Varela Round, sans-serif", name: "Varela Round" },
    { value: "Vast Shadow, cursive", name: "Vast Shadow" },
    { value: "Vesper Libre, serif", name: "Vesper Libre" },
    { value: "Viaoda Libre, cursive", name: "Viaoda Libre" },
    { value: "Vibes, cursive", name: "Vibes" },
    { value: "Vibur, cursive", name: "Vibur" },
    { value: "Vidaloka, serif", name: "Vidaloka" },
    { value: "Viga, sans-serif", name: "Viga" },
    { value: "Voces, cursive", name: "Voces" },
    { value: "Volkhov, serif", name: "Volkhov" },
    { value: "Vollkorn, serif", name: "Vollkorn" },
    { value: "Voltaire, sans-serif", name: "Voltaire" },
    { value: "Waiting for the Sunrise, cursive", name: "Waiting for the Sunrise" },
    { value: "Wallpoet, cursive", name: "Wallpoet" },
    { value: "Walter Turncoat, cursive", name: "Walter Turncoat" },
    { value: "Warnes, cursive", name: "Warnes" },
    { value: "Wellfleet, cursive", name: "Wellfleet" },
    { value: "Wendy One, sans-serif", name: "Wendy One" },
    { value: "Wire One, sans-serif", name: "Wire One" },
    { value: "Yanone Kaffeesatz, sans-serif", name: "Yanone Kaffeesatz" },
    { value: "Yantramanav, sans-serif", name: "Yantramanav" },
    { value: "Yatra One, cursive", name: "Yatra One" },
    { value: "Yellowtail, cursive", name: "Yellowtail" },
    { value: "Yeon Sung, cursive", name: "Yeon Sung" },
    { value: "Yeseva One, serif", name: "Yeseva One" },
    { value: "Yesteryear, cursive", name: "Yesteryear" },
    { value: "Yrsa, serif", name: "Yrsa" },
    { value: "ZCOOL KuaiLe, cursive", name: "ZCOOL KuaiLe" },
    { value: "ZCOOL QingKe HuangYou, cursive", name: "ZCOOL QingKe HuangYou" },
    { value: "ZCOOL XiaoWei, serif", name: "ZCOOL XiaoWei" },
    { value: "Zen Antique, serif", name: "Zen Antique" },
    { value: "Zen Antique Soft, serif", name: "Zen Antique Soft" },
    { value: "Zen Dots, cursive", name: "Zen Dots" },
    { value: "Zen Kaku Gothic Antique, sans-serif", name: "Zen Kaku Gothic Antique" },
    { value: "Zen Kaku Gothic New, sans-serif", name: "Zen Kaku Gothic New" },
    { value: "Zen Kurenaido, sans-serif", name: "Zen Kurenaido" },
    { value: "Zen Loop, cursive", name: "Zen Loop" },
    { value: "Zen Maru Gothic, sans-serif", name: "Zen Maru Gothic" },
    { value: "Zen Old Mincho, serif", name: "Zen Old Mincho" },
    { value: "Zen Tokyo Zoo, cursive", name: "Zen Tokyo Zoo" },
    { value: "Zeyada, cursive", name: "Zeyada" },
    { value: "Zhi Mang Xing, cursive", name: "Zhi Mang Xing" },
    { value: "Zilla Slab, serif", name: "Zilla Slab" },
    { value: "Zilla Slab Highlight, cursive", name: "Zilla Slab Highlight" }
]; 